name: ai_werkstatt_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - cpuonly
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - notebook
  - pip
  - pip:
      - uni2ts        # Salesforce Moirai
      - timesfm       # Google TimesFM
      - gluonts       # Wichtig für Evaluation
      - datasetsforecast      # Für den M4 Download
      - git+https://github.com/amazon-science/chronos-forecasting.git

#Ausführen mit conda env create -f environment.yml